package com.donutsmp.gamehub.screen;

import com.donutsmp.gamehub.GameHubClient;import com.donutsmp.gamehub.HubSession;import com.donutsmp.gamehub.config.HubConfig;import com.donutsmp.gamehub.game.Game;import com.donutsmp.gamehub.money.AmountParser;import com.donutsmp.gamehub.money.MoneyFormat;import com.donutsmp.gamehub.net.BetRequest;import com.donutsmp.gamehub.net.BetResponse;import net.minecraft.client.gui.DrawContext;import net.minecraft.client.gui.screen.Screen;import net.minecraft.client.gui.widget.ButtonWidget;import net.minecraft.client.gui.widget.TextFieldWidget;import net.minecraft.text.Text;import java.util.*;
public final class GameScreen extends Screen {private static final java.util.regex.Pattern MULTIPLIER_FORMAT=java.util.regex.Pattern.compile("^\\d{1,3}(\\.\\d{1,2})?x$");private final Screen parent;private final HubSession session;private final Game game;private TextFieldWidget betField;private final List<ButtonWidget> playButtons=new ArrayList<>();private int px,py,pw,ph;private boolean busy;private String message="";private int messageColor=Theme.MUTED;private String multiplierText="";private int multiplierColor=Theme.MUTED;private String pendingId,pendingKey;
 public GameScreen(Screen parent,HubSession session,Game game){super(Text.literal(game.title()));this.parent=parent;this.session=session;this.game=game;}
 @Override protected void init(){playButtons.clear();pw=Math.max(240,Math.min(width-24,400));ph=164+(game.usesBet()?0:-36)+28;px=(width-pw)/2;py=Math.max(6,(height-ph)/2);int y=py+100+(game.usesBet()?0:-36);if(game.usesBet()){betField=new TextFieldWidget(textRenderer,px+10,py+64,pw-20,18,Text.literal("Bet"));betField.setMaxLength(24);betField.setPlaceholder(Text.literal("Bet amount (e.g. 500k, 1.5m, 2000000)"));addDrawableChild(betField);}int n=game.selections().isEmpty()?1:game.selections().size(),gap=6,bw=(pw-20-gap*(n-1))/n;for(int i=0;i<n;i++){String id=game.selections().isEmpty()?null:game.selections().get(i).id();String label=game.selections().isEmpty()?"PLAY":game.selections().get(i).label();ButtonWidget b=ButtonWidget.builder(Text.literal(label),btn->submit(id)).dimensions(px+10+i*(bw+gap),y,bw,24).build();playButtons.add(addDrawableChild(b));}addDrawableChild(ButtonWidget.builder(Text.literal("Back"),btn->close()).dimensions(px+10,py+ph-26,60,18).build());}
 @Override public void tick(){HubConfig c=session.config();boolean ok=c!=null&&c.isEnabled(game)&&!busy;for(ButtonWidget b:playButtons)b.active=ok;}
 private void submit(String selection){HubConfig c=session.config();if(busy||c==null||!c.isEnabled(game)||session.backend()==null)return;long bet=0;if(game.usesBet()){AmountParser.ParseResult r=AmountParser.parse(betField.getText());if(!r.ok()){show(r.error(),Theme.BAD);return;}bet=r.value();}if(client.player==null)return;String key=game.id()+"|"+bet+"|"+selection;if(pendingId==null||!key.equals(pendingKey)){pendingId=UUID.randomUUID().toString();pendingKey=key;}String txId=pendingId;BetRequest req=new BetRequest(txId,client.player.getUuid().toString(),game.id(),bet,selection);busy=true;multiplierText="";show("Waiting for server...",Theme.MUTED);session.backend().postBet(req).whenComplete((resp,err)->client.execute(()->{busy=false;if(err!=null){GameHubClient.LOGGER.warn("Bet request failed",err);show("Network error; pressing again retries the same transaction.",Theme.BAD);return;}handle(txId,resp);}));}
 private void handle(String txId,BetResponse resp){if(resp.transactionId==null||!resp.transactionId.equals(txId)){show("Ignored a response for a different transaction.",Theme.BAD);return;}pendingId=null;pendingKey=null;if(!resp.accepted){show("Rejected: "+clean(resp.reason),Theme.BAD);return;}String result=clean(resp.result);boolean loss="LOSE".equalsIgnoreCase(result);show("Result: "+result+(game.usesBet()?"   Bet "+MoneyFormat.compact(resp.bet)+"   Payout "+MoneyFormat.compact(resp.payout):""),loss?Theme.BAD:Theme.GOOD);String m=resp.multiplier;if(game.usesBet()&&m!=null&&MULTIPLIER_FORMAT.matcher(m).matches()){multiplierText="Multiplier: "+m;multiplierColor=loss?Theme.BAD:Theme.GOOD;}}
 private void show(String text,int color){message=text;messageColor=color;}private static String clean(String s){if(s==null)return"-";s=s.replace('\u00a7',' ');return s.length()>100?s.substring(0,100)+"...":s;}
 @Override public void renderBackground(DrawContext ctx,int mouseX,int mouseY,float delta){super.renderBackground(ctx,mouseX,mouseY,delta);Theme.panel(ctx,px,py,pw,ph);ctx.drawCenteredTextWithShadow(textRenderer,Text.literal(game.title()),width/2,py+10,Theme.TEXT);HubConfig c=session.config();if(c==null)ctx.drawCenteredTextWithShadow(textRenderer,Text.literal(session.status()),width/2,py+26,Theme.BAD);else if(!c.isEnabled(game))ctx.drawCenteredTextWithShadow(textRenderer,Text.literal("This game is disabled by the server"),width/2,py+26,Theme.BAD);else if(game.usesBet()){ctx.drawTextWithShadow(textRenderer,Text.literal("Min "+MoneyFormat.compact(c.minimumBet())+"   Max "+MoneyFormat.compact(c.maximumBet())),px+10,py+26,Theme.MUTED);ctx.drawTextWithShadow(textRenderer,Text.literal("Pay: "+c.payCommand()),px+10,py+40,Theme.TEXT);String hint;int hintColor=Theme.MUTED;AmountParser.ParseResult r=AmountParser.parse(betField==null?"":betField.getText());if(betField!=null&&betField.getText().isBlank())hint="";else if(!r.ok()){hint=r.error();hintColor=Theme.BAD;}else hint="= "+MoneyFormat.grouped(r.value());ctx.drawTextWithShadow(textRenderer,Text.literal(hint),px+10,py+84,hintColor);}else{ctx.drawTextWithShadow(textRenderer,Text.literal("No bet needed. Pick a crate."),px+10,py+26,Theme.MUTED);StringBuilder prices=new StringBuilder();for(Game.Selection s:game.selections()){Long p=c.cratePrices().get(s.id());if(p!=null)prices.append(s.label()).append(' ').append(MoneyFormat.compact(p)).append("   ");}ctx.drawTextWithShadow(textRenderer,Text.literal(prices.toString().trim()),px+10,py+40,Theme.MUTED);}if(!multiplierText.isEmpty())ctx.drawCenteredTextWithShadow(textRenderer,Text.literal(multiplierText),width/2,py+ph-62,multiplierColor);ctx.drawCenteredTextWithShadow(textRenderer,Text.literal(message),width/2,py+ph-48,messageColor);}
 @Override public void close(){client.setScreen(parent);}}
