package com.donutsmp.gamehub.screen;

import com.donutsmp.gamehub.GameHubClient;import com.donutsmp.gamehub.HubSession;import com.donutsmp.gamehub.config.HubConfig;import com.donutsmp.gamehub.game.Game;import com.donutsmp.gamehub.money.AmountParser;import com.donutsmp.gamehub.money.MoneyFormat;import net.minecraft.client.gui.DrawContext;import net.minecraft.client.gui.screen.Screen;import net.minecraft.client.gui.widget.ButtonWidget;import net.minecraft.client.gui.widget.TextFieldWidget;import net.minecraft.text.Text;import java.util.*;
public final class GameScreen extends Screen {private final Screen parent;private final HubSession session;private final Game game;private TextFieldWidget betField;private final List<ButtonWidget> playButtons=new ArrayList<>();private int px,py,pw,ph;private boolean busy;private String message="";private int messageColor=Theme.MUTED;
 public GameScreen(Screen parent,HubSession session,Game game){super(Text.literal(game.usesBet()?"Pay":game.title()));this.parent=parent;this.session=session;this.game=game;}
 @Override protected void init(){playButtons.clear();pw=Math.max(240,Math.min(width-24,400));ph=164+(game.usesBet()?0:-36)+28;px=(width-pw)/2;py=Math.max(6,(height-ph)/2);int y=py+100+(game.usesBet()?0:-36);if(game.usesBet()){betField=new TextFieldWidget(textRenderer,px+10,py+64,pw-20,18,Text.literal("Amount"));betField.setMaxLength(24);betField.setPlaceholder(Text.literal("Payment amount (e.g. 500k, 1.5m, 2000000)"));addDrawableChild(betField);}int n=game.selections().isEmpty()?1:game.selections().size(),gap=6,bw=(pw-20-gap*(n-1))/n;for(int i=0;i<n;i++){String id=game.selections().isEmpty()?null:game.selections().get(i).id();String label=game.usesBet()?"PAY":(game.selections().isEmpty()?"PLAY":game.selections().get(i).label());ButtonWidget b=ButtonWidget.builder(Text.literal(label),btn->submit(id)).dimensions(px+10+i*(bw+gap),y,bw,24).build();playButtons.add(addDrawableChild(b));}addDrawableChild(ButtonWidget.builder(Text.literal("Back"),btn->close()).dimensions(px+10,py+ph-26,60,18).build());}
 @Override public void tick(){HubConfig c=session.config();boolean ok=c!=null&&c.isEnabled(game)&&!busy;for(ButtonWidget b:playButtons)b.active=ok;}
 private void submit(String selection){HubConfig c=session.config();if(busy||c==null||!game.usesBet())return;AmountParser.ParseResult r=AmountParser.parse(betField==null?"":betField.getText());if(!r.ok()){show(r.error(),Theme.BAD);return;}long amount=r.value();if(client.player==null)return;String target=c.paymentTarget();if(target==null||target.isBlank()){show("Payment target is not configured.",Theme.BAD);return;}busy=true;try{client.player.networkHandler.sendChatCommand("pay "+target+" "+amount);show("Payment command sent: /pay "+target+" "+MoneyFormat.compact(amount),Theme.GOOD);}catch(RuntimeException e){GameHubClient.LOGGER.warn("Payment command failed",e);show("Could not send the payment command.",Theme.BAD);}finally{busy=false;}}

 private void show(String text,int color){message=text;messageColor=color;}
 @Override public void renderBackground(DrawContext ctx,int mouseX,int mouseY,float delta){super.renderBackground(ctx,mouseX,mouseY,delta);Theme.panel(ctx,px,py,pw,ph);ctx.drawCenteredTextWithShadow(textRenderer,Text.literal(game.title()),width/2,py+10,Theme.TEXT);HubConfig c=session.config();if(c==null)ctx.drawCenteredTextWithShadow(textRenderer,Text.literal(session.status()),width/2,py+26,Theme.BAD);else if(!c.isEnabled(game))ctx.drawCenteredTextWithShadow(textRenderer,Text.literal("This game is disabled by the server"),width/2,py+26,Theme.BAD);else if(game.usesBet()){ctx.drawTextWithShadow(textRenderer,Text.literal("Min Amount "+MoneyFormat.compact(c.minimumBet())+"   Max Amount "+MoneyFormat.compact(c.maximumBet())),px+10,py+26,Theme.MUTED);ctx.drawTextWithShadow(textRenderer,Text.literal("Payment: "+c.payCommand()),px+10,py+40,Theme.TEXT);String hint;int hintColor=Theme.MUTED;AmountParser.ParseResult r=AmountParser.parse(betField==null?"":betField.getText());if(betField!=null&&betField.getText().isBlank())hint="";else if(!r.ok()){hint=r.error();hintColor=Theme.BAD;}else hint="= "+MoneyFormat.grouped(r.value());ctx.drawTextWithShadow(textRenderer,Text.literal(hint),px+10,py+84,hintColor);}else{ctx.drawTextWithShadow(textRenderer,Text.literal("No bet needed. Pick a crate."),px+10,py+26,Theme.MUTED);StringBuilder prices=new StringBuilder();for(Game.Selection s:game.selections()){Long p=c.cratePrices().get(s.id());if(p!=null)prices.append(s.label()).append(' ').append(MoneyFormat.compact(p)).append("   ");}ctx.drawTextWithShadow(textRenderer,Text.literal(prices.toString().trim()),px+10,py+40,Theme.MUTED);}ctx.drawCenteredTextWithShadow(textRenderer,Text.literal(message),width/2,py+ph-48,messageColor);}
 @Override public void close(){client.setScreen(parent);}}
