package com.donutsmp.gamehub.screen;
import com.donutsmp.gamehub.HubSession;import com.donutsmp.gamehub.config.HubConfig;import com.donutsmp.gamehub.game.Game;import com.donutsmp.gamehub.money.MoneyFormat;import net.minecraft.client.gui.DrawContext;import net.minecraft.client.gui.screen.Screen;import net.minecraft.client.gui.widget.ButtonWidget;import net.minecraft.text.Text;import java.util.*;
public final class HubScreen extends Screen {
 private static final int BTN_H=24,GAP=6;private final Screen parent;private final HubSession session;private final Map<Game,ButtonWidget> gameButtons=new EnumMap<>(Game.class);private ButtonWidget copyButton,refreshButton;private int px,py,pw,ph;
 public HubScreen(Screen parent,HubSession session){super(Text.literal("DonutSMP Game Hub"));this.parent=parent;this.session=session;}
 @Override protected void init(){gameButtons.clear();pw=Math.max(240,Math.min(width-24,400));ph=96+3*(BTN_H+GAP)+30;px=(width-pw)/2;py=Math.max(6,(height-ph)/2);int bw=(pw-30)/2,top=py+96;Game[] games=Game.values();for(int i=0;i<games.length;i++){Game g=games[i];int x=px+10+(i%2)*(bw+10),y=top+(i/2)*(BTN_H+GAP);ButtonWidget b=ButtonWidget.builder(Text.literal(g.title()),btn->client.setScreen(new GameScreen(this,session,g))).dimensions(x,y,bw,BTN_H).build();b.active=false;gameButtons.put(g,addDrawableChild(b));}copyButton=addDrawableChild(ButtonWidget.builder(Text.literal("Copy"),btn->{HubConfig c=session.config();if(c!=null)client.keyboard.setClipboard(c.payCommand());}).dimensions(px+pw-54,py+44,44,16).build());refreshButton=addDrawableChild(ButtonWidget.builder(Text.literal("Refresh"),btn->session.refresh()).dimensions(px+10,py+ph-26,60,18).build());addDrawableChild(ButtonWidget.builder(Text.literal("Close"),btn->close()).dimensions(px+pw-70,py+ph-26,60,18).build());}
 @Override public void tick(){HubConfig c=session.config();for(var e:gameButtons.entrySet())e.getValue().active=c!=null&&c.isEnabled(e.getKey());copyButton.active=c!=null;refreshButton.active=!session.loading()&&session.backend()!=null;}
 @Override public void renderBackground(DrawContext ctx,int mouseX,int mouseY,float delta){super.renderBackground(ctx,mouseX,mouseY,delta);Theme.panel(ctx,px,py,pw,ph);ctx.drawCenteredTextWithShadow(textRenderer,Text.literal("DonutSMP Game Hub"),width/2,py+10,Theme.TEXT);HubConfig c=session.config();int y=py+28;if(c==null){ctx.drawCenteredTextWithShadow(textRenderer,Text.literal(session.status()),width/2,y,Theme.BAD);ctx.drawTextWithShadow(textRenderer,Text.literal("Pay: -"),px+10,py+48,Theme.MUTED);ctx.drawTextWithShadow(textRenderer,Text.literal("Bet limits: -"),px+10,py+66,Theme.MUTED);}else{ctx.drawCenteredTextWithShadow(textRenderer,Text.literal(session.status()),width/2,y,Theme.GOOD);ctx.drawTextWithShadow(textRenderer,Text.literal(c.payCommand()),px+10,py+48,Theme.TEXT);ctx.drawTextWithShadow(textRenderer,Text.literal("Min bet "+MoneyFormat.compact(c.minimumBet())+"   Max bet "+MoneyFormat.compact(c.maximumBet())),px+10,py+66,Theme.MUTED);}ctx.drawTextWithShadow(textRenderer,Text.literal("Choose a game"),px+10,py+84,Theme.MUTED);}
 @Override public void close(){client.setScreen(parent);}
}
